version: "3"
services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - TZ=${DB_TZ:-UTC+3}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DATABASE=${DB_DATABASE}
      - PGPORT=${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_data:
