version: "3"
services:
  lead_stream_api:
    build: lead_stream_api
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      PRE_START_PATH: /app/scripts/prestart.sh
    depends_on:
      - postgres
    ports:
      - "8000"
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - TZ=${DB_TZ:-UTC+3}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DATABASE=${DB_DATABASE}
      - PGPORT=${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    profiles:
      - donotstart
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    ports:
      - "${PGADMIN_PORT:-5050}:80"
volumes:
  postgres_data:
  pgadmin_data: